### ISSUE TITLE
Ability to add default path for target folder in template file

### ISSUE THREAD

**Issue by harveycubewise** [harvey-withington/Folder-Templates#4]
It would be useful to be able to add a default (relative to the template top level folder, or absolute) path for the current template. This would just pre-populate the Destination Folder textbox, allowing the user to override it in the UI.

For example, template file path: C:\ABC\DEF\Templates\my_template\.ft\template.json and in template.json:

```
{
    "name": "Template Name",
    "defaultDestinationFolder": "..\Folders",
    "parameters": { ... }
}
```

If left default, the template would exist in "Templates", but create folders in "Folders". This would likely be common scenario.

**Comment by harvey-withington** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ability to add default path for target folder in template file](https://trello.com/c/dTqEadgK/11-ability-to-add-default-path-for-target-folder-in-template-file)
